---
- name: install ansible-docker depencendies
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items:
  - docker-python

- name: pull nginx-slim image (custom)
  docker_image:
    name: "{{ custom_registry }}/google_containers/nginx-slim"
    tag: "{{ gcr_proxy_nginx }}"
  register: nginx_exists
  ignore_errors: yes

- name: pull nginx-slim image (gcr.io)
  docker_image:
    repository: "{{ custom_registry }}/google_containers/nginx-slim"
    name: "gcr.io/google_containers/nginx-slim"
    tag: "{{ gcr_proxy_nginx }}"
    push: yes
  when:
  - nginx_exists | failed

- name: copy nginx.conf
  template: src=nginx.conf.j2 dest=/vagrant/nginx.conf force=yes mode=0644

- name: start proxy container
  docker_container:
    name: gcr_proxy
    image: "google_containers/nginx-slim:{{ gcr_proxy_nginx }}"
    ports:
    - "80:80"
    state: started
    restart_policy: always
    volumes:
    - /vagrant/nginx.conf:/etc/nginx/nginx.conf:ro
