- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Make sure cache directory exists
      file:
        path: "{{ vagrant_home }}/cache/{{ ansible_distribution }}/{{ ansible_distribution_version }}/"
        state: directory
      when: vagrant_cache

- hosts: master
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  tasks:
    - include_role:
        name: master
        tasks_from: yum_cache.yml
      when: vagrant_cache
