---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    storage: glusterfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/var/lib/glusterfs-container"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
  labels:
    storage: glusterfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/var/lib/glusterfs-container"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    storage: glusterfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/var/lib/glusterfs-container"
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs
  labels:
    glusterfs: service
spec:
  ports:
  - port: 24007
    name: glusterd
  - port: 24006
    name: glusterblockd
  - port: 3260
    name: iscsi
  clusterIP: None
  selector:
    glusterfs: pod
---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: glusterfs
  labels:
    glusterfs: statefulset
  annotations:
    description: GlusterFS StatefulSet
    tags: glusterfs
spec:
  selector:
    matchLabels:
      glusterfs: pod
  serviceName: glusterfs
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: glusterfs
      labels:
        glusterfs: pod
        glusterfs-node: pod
    spec:
      nodeSelector:
        storagenode: glusterfs
      containers:
      - image: jarrpa/gluster-fedora-minimal:dev
        imagePullPolicy: IfNotPresent
        name: glusterfs
        ports:
        - containerPort: 3260
        - containerPort: 24006
        - containerPort: 24007
        env:
        - name: GB_GLFS_LRU_COUNT
          value: "15"
        - name: TCMU_LOGDIR
          value: "/var/log/glusterfs/gluster-block"
        - name: GB_LOGDIR
          value: "/var/log/glusterfs/gluster-block"
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: glusterfs-state
          mountPath: "/glusterfs"
        - name: glusterfs-dev
          mountPath: "/dev"
        - name: glusterfs-cgroup
          mountPath: "/sys/fs/cgroup"
          readOnly: true
        - name: glusterfs-ssl
          mountPath: "/etc/ssl"
          readOnly: true
        securityContext:
          capabilities: {}
          privileged: true
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          tcpSocket:
            port: 24007
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 50
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          tcpSocket:
            port: 24007
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 50
      volumes:
      - name: glusterfs-dev
        hostPath:
          path: "/dev"
      - name: glusterfs-cgroup
        hostPath:
          path: "/sys/fs/cgroup"
      - name: glusterfs-ssl
        hostPath:
          path: "/etc/ssl"
      - name: kernel-modules
        hostPath:
          path: "/usr/lib/modules"
  volumeClaimTemplates:
  - metadata:
      name: glusterfs-state
    spec:
      selector:
        matchLabels:
          storage: glusterfs
      accessModes: [ "ReadWriteMany" ]
      storageClassName: ""
      resources:
        requests:
          storage: 1Gi
