kind: Service
apiVersion: v1
metadata:
  name: nginx
  annotations:
    description: Exposes nginx service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    name: nginx-pod1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    name: nginx-pod1
spec:
  containers:
  - name: nginx-pod1
    image: gcr.io/google_containers/nginx-slim:0.24
    imagePullPolicy: IfNotPresent
    ports:
    - name: web
      containerPort: 80
    securityContext:
      privileged: true
    volumeMounts:
    - name: gluster-vol1
      mountPath: /usr/share/nginx/html
  volumes:
  - name: gluster-vol1
    persistentVolumeClaim:
      claimName: gluster1
